# Generated by Django 4.1.4 on 2023-04-13 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField(default='', verbose_name='账号')),
                ('user_pwd', models.TextField(default='', verbose_name='密码')),
            ],
        ),
    ]
