# Generated by Django 4.1.4 on 2023-04-13 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='suggest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField(default='', verbose_name='帐号')),
                ('novel_name', models.TextField(default='', verbose_name='小说名')),
                ('flag', models.TextField(default=0, verbose_name='标记')),
                ('time', models.DateTimeField(default='', verbose_name='更新时间')),
            ],
        ),
    ]
